ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      me.SerializationKt.configureSerialization
      me.StatusPagesKt.configureStatusPages
      me.RoutingKt.configureRouting
    ]
  }
}

slack {
    signingSecret = ${?SLACK_SIGNING_SECRET}
    botToken = ${?SLACK_BOT_OAUTH_TOKEN}
}